---
# encrypt this file before committing
# ansible-vault encrypt inventories/production/group_vars/vault.yml

vault_user:       "netadmin"
vault_pass:       "CHANGE_ME"
vault_enable:     "CHANGE_ME"
vault_tacacs_key: "CHANGE_ME"
vault_snmp_user:  "snmpv3user"
vault_snmp_auth:  "CHANGE_ME"
vault_snmp_priv:  "CHANGE_ME"
vault_ntp_key:    "CHANGE_ME"
