---
- name: Create backup folder
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0750'
  delegate_to: localhost

- name: Pull running config
  cisco.ios.ios_command:
    commands:
      - "show running-config"
  register: running_cfg

- name: Write config to file
  ansible.builtin.copy:
    content: "{{ running_cfg.stdout[0] }}"
    dest: "{{ backup_dir }}/{{ inventory_hostname }}_{{ ansible_date_time.epoch }}.cfg"
    mode: '0640'
  delegate_to: localhost
