---
- name: login banner
  ios_banner:
    banner: login
    text: "{{ login_banner }}"
    state: present
  when: not check_only | bool
  tags: banners

- name: motd banner
  ios_banner:
    banner: motd
    text: "{{ login_banner }}"
    state: present
  when: not check_only | bool
  tags: banners
