---
- name: Login banner
  cisco.ios.ios_banner:
    banner: login
    text: "{{ login_banner }}"
    state: present
  when: not hardening_check_only | bool
  tags: banners

- name: MOTD banner
  cisco.ios.ios_banner:
    banner: motd
    text: "{{ login_banner }}"
    state: present
  when: not hardening_check_only | bool
  tags: banners
