---
- name: Set buffer size
  cisco.ios.ios_config:
    lines:
      - "logging buffered {{ log_buf_size }} {{ log_level }}"
  when: not hardening_check_only | bool
  tags: logging

- name: Remote syslog servers
  cisco.ios.ios_config:
    lines:
      - "logging host {{ item.host }} transport udp port {{ item.port }}"
  loop: "{{ log_servers }}"
  when: not hardening_check_only | bool
  tags: logging

- name: Source interface for logs
  cisco.ios.ios_config:
    lines:
      - "logging source-interface {{ log_src_iface }}"
  when: not hardening_check_only | bool
  tags: logging

- name: Timestamps and login tracking
  cisco.ios.ios_config:
    lines:
      - "logging on"
      - "logging trap {{ log_level }}"
      - "service timestamps log datetime msec localtime show-timezone"
      - "service timestamps debug datetime msec localtime show-timezone"
      - "login on-failure log every 3"
      - "login on-success log every 10"
  when: not hardening_check_only | bool
  tags: logging
