---
- name: enable ntp authentication
  ios_config:
    lines:
      - "ntp authenticate"
      - "ntp authentication-key {{ ntp_key_id }} md5 {{ ntp_key }}"
      - "ntp trusted-key {{ ntp_key_id }}"
  no_log: true
  when: not check_only | bool
  tags: ntp

- name: add ntp servers
  ios_config:
    lines:
      - "ntp server {{ item }} key {{ ntp_key_id }} prefer"
  loop: "{{ ntp_servers }}"
  when: not check_only | bool
  tags: ntp

- name: set timezone utc
  ios_config:
    lines:
      - "clock timezone UTC 0 0"
  when: not check_only | bool
  tags: ntp
