---
- name: minimum password length
  ios_config:
    lines:
      - "security passwords min-length {{ pw_min_len }}"
  when: not check_only | bool
  tags: passwords

# block logins for 2 min after 5 failures in 60 seconds
- name: brute force protection
  ios_config:
    lines:
      - "login block-for 120 attempts 5 within 60"
      - "login delay 3"
      - "security authentication failure rate 3 log"
  when: not check_only | bool
  tags: passwords

- name: enable secret using scrypt
  ios_config:
    lines:
      - "enable algorithm-type scrypt secret {{ vault_enable }}"
  no_log: true
  when: not check_only | bool
  tags: passwords
