---
- name: Disable small servers
  cisco.ios.ios_config:
    lines:
      - "no service tcp-small-servers"
      - "no service udp-small-servers"
  when: not hardening_check_only | bool
  tags: services

- name: Turn off HTTP server
  cisco.ios.ios_config:
    lines:
      - "no ip http server"
      - "no ip http secure-server"
  when: not hardening_check_only | bool
  tags: services

- name: Disable IP source routing
  cisco.ios.ios_config:
    lines:
      - "no ip source-route"
  when: not hardening_check_only | bool
  tags: services

- name: TCP keepalives
  cisco.ios.ios_config:
    lines:
      - "service tcp-keepalives-in"
      - "service tcp-keepalives-out"
  when: not hardening_check_only | bool
  tags: services

- name: Password encryption service
  cisco.ios.ios_config:
    lines:
      - "service password-encryption"
  when: not hardening_check_only | bool
  tags: services

- name: Disable PAD
  cisco.ios.ios_config:
    lines:
      - "no service pad"
  when: not hardening_check_only | bool
  tags: services

- name: Disable finger service
  cisco.ios.ios_config:
    lines:
      - "no service finger"
  when: not hardening_check_only | bool
  tags: services
