---
hardening_run_ssh: true
hardening_run_aaa: true
hardening_run_ntp: true
hardening_run_logging: true
hardening_run_snmp: true
hardening_run_services: true
hardening_run_passwords: true
hardening_run_banners: true

hardening_backup_first: true
hardening_check_only: false

hardening_backup_dir: "backups/{{ inventory_hostname }}/{{ ansible_date_time.date }}"
hardening_cfg_timeout: 60
