---
all:
  children:
    cisco_routers:
      hosts:
        devnet-cat8k:
          ansible_host: 10.10.20.48
          device_role: core_router
      vars:
        ansible_network_os: ios
        ansible_connection: network_cli
        ansible_become: yes
        ansible_become_method: enable

    network_devices:
      children:
        cisco_routers: